spring.application.name=mediguide-ai
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=qwen2.5:7b
spring.ai.ollama.embedding.model=bge-m3:latest
spring.datasource.url=jdbc:postgresql://localhost:5432/mediguide
spring.datasource.username=mediguide
spring.datasource.password=mediguide123
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.ai.vectorstore.pgvector.dimensions=1536
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.data.redis.host=localhost
spring.data.redis.port=6379
server.port=8083
